apiVersion: v1
kind: Pod
metadata:
  name: mintnodeapp-pod
  labels:
    app: mintnodeapp
spec:
  containers:
  - name: mintnodeapp
    image: sgaz204:v1
    resources:
      limits:
        memory: "256Mi"
        cpu: "500m"
    livenessProbe:
      httpGet:
        path: /
        port: 8888
      initialDelaySeconds: 5
      periodSeconds: 30
    ports:
    - containerPort: 8888
