apiVersion: v1
kind: Pod
metadata:
  name: mintnodeapp-pod
  labels:
    app: mintnodeapp
spec:
  containers:
  - name: mintnodeapp
    image: abhishekkant/xxxxapp
    resources:
      limits:
        memory: "256Mi"
        cpu: "500m"
    livenessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 10
    ports:
    - containerPort: 8080
  nodeSelector:
    purpose: training
